const FLAG_MAP: Record<string, string> = {
  'Algeria':                  '/Flags_PNG/Algeria.png',
  'Argentina':                '/Flags_PNG/Argentina.png',
  'Australia':                '/Flags_PNG/Australia.png',
  'Austria':                  '/Flags_PNG/Austria.png',
  'Belgium':                  '/Flags_PNG/Belgium.png',
  'Bosnia and Herzegovina':   '/Flags_PNG/Bosnia_Herzegovina.png',
  'Bosnia-Herzegovina':       '/Flags_PNG/Bosnia_Herzegovina.png',
  'Brazil':                   '/Flags_PNG/Brazil.png',
  'Canada':                   '/Flags_PNG/Canada.png',
  'Cape Verde':               '/Flags_PNG/Cape_Verde_Islands.png',
  'Cape Verde Islands':       '/Flags_PNG/Cape_Verde_Islands.png',
  'Colombia':                 '/Flags_PNG/Colombia.png',
  'Congo DR':                 '/Flags_PNG/Congo.png',
  'DR Congo':                 '/Flags_PNG/Congo.png',
  'Croatia':                  '/Flags_PNG/Croatia.png',
  "Côte d'Ivoire":            '/Flags_PNG/Ivory_Coast.png',
  "Cote d'Ivoire":            '/Flags_PNG/Ivory_Coast.png',
  'Ivory Coast':              '/Flags_PNG/Ivory_Coast.png',
  'Curaçao':                  '/Flags_PNG/Curacao.png',
  'Curacao':                  '/Flags_PNG/Curacao.png',
  'Czech Republic':           '/Flags_PNG/Czechia.png',
  'Czechia':                  '/Flags_PNG/Czechia.png',
  'Ecuador':                  '/Flags_PNG/Ecuador.png',
  'Egypt':                    '/Flags_PNG/Egypt.png',
  'England':                  '/Flags_PNG/England.png',
  'France':                   '/Flags_PNG/France.png',
  'Germany':                  '/Flags_PNG/Germany.png',
  'Ghana':                    '/Flags_PNG/Ghana.png',
  'Haiti':                    '/Flags_PNG/Haiti.png',
  'Iran':                     '/Flags_PNG/Iran.png',
  'Iraq':                     '/Flags_PNG/Iraq.png',
  'Japan':                    '/Flags_PNG/Japan.png',
  'Jordan':                   '/Flags_PNG/Jordan.png',
  'Korea Republic':           '/Flags_PNG/South_Korea.png',
  'South Korea':              '/Flags_PNG/South_Korea.png',
  'Mexico':                   '/Flags_PNG/Mexico.png',
  'Morocco':                  '/Flags_PNG/Morocco.png',
  'Netherlands':              '/Flags_PNG/Netherlands.png',
  'New Zealand':              '/Flags_PNG/New_Zealand.png',
  'Norway':                   '/Flags_PNG/Norway.png',
  'Panama':                   '/Flags_PNG/Panama.png',
  'Paraguay':                 '/Flags_PNG/Paraguay.png',
  'Portugal':                 '/Flags_PNG/Portugal.png',
  'Qatar':                    '/Flags_PNG/Qatar.png',
  'Saudi Arabia':             '/Flags_PNG/Saudi_Arabia.png',
  'Scotland':                 '/Flags_PNG/Scotland.png',
  'Senegal':                  '/Flags_PNG/Senegal.png',
  'South Africa':             '/Flags_PNG/South_Africa.png',
  'Spain':                    '/Flags_PNG/Spain.png',
  'Sweden':                   '/Flags_PNG/Sweden.png',
  'Switzerland':              '/Flags_PNG/Switzerland.png',
  'Tunisia':                  '/Flags_PNG/Tunisia.png',
  'Turkey':                   '/Flags_PNG/Turkey.png',
  'Uruguay':                  '/Flags_PNG/Uruguay.png',
  'USA':                      '/Flags_PNG/USA.png',
  'United States':            '/Flags_PNG/USA.png',
  'Uzbekistan':               '/Flags_PNG/Uzbekistan.png',
};

/** Returns the local round flag path for a team, or falls back to the API crest URL. */
export function getTeamFlag(teamName: string, fallbackCrest?: string | null): string | null {
  return FLAG_MAP[teamName] ?? fallbackCrest ?? null;
}
